// Copyright (c) 2025 Mark Anthony Taylor. All rights reserved. Email: mark.anthony.taylor@gmail.com.
// Bundle generated by Build.Rococo.GUI.cs on Oct 2025 UTC
// Origin: D:\work\rococo\UE5\RococoTestFPS\Plugins\RococoGui\Source\RococoGui\Private\GameOptionBuilder.cpp
// Copyright (c) 2025 Mark Anthony Taylor. All rights reserved. Email: mark.anthony.taylor@gmail.com.
#include <GameOptionBuilder.h>

void IRococoGameOptionBuilder::RaiseError(const FString& methodMsg, const FString& propertyMsg, const FString& errMsg)
{
	OnError(methodMsg, propertyMsg, errMsg);
}

void IRococoGameOptionBuilder::Accept()
{
	OnAccept();
}

void IRococoGameOptionBuilder::Revert()
{
	OnRevert();
}

void IRococoGameOptionBuilder::InvokeInitOptions()
{
	InitOptions();
}

FString IRococoGameOptionBuilder::RaiseGetOptionId()
{
	return TEXT("IRococoGameOptionBuilder: RaiseGetOptionId - default");
}

