// Copyright (c) 2025 Mark Anthony Taylor. All rights reserved. Email: mark.anthony.taylor@gmail.com.
// Bundle generated by Build.Rococo.GUI.cs on Oct 2025 UTC
// Origin: D:\work\rococo\UE5\RococoTestFPS\Plugins\RococoGui\Source\RococoGui\Private\RococoGui_BPEvents.cpp
// Copyright (c) 2025 Mark Anthony Taylor. All rights reserved. Email: mark.anthony.taylor@gmail.com.
#include <RococoGui_BPevents.h>

void IRococoReflectionEventHandler::RaiseBadMethod(const FString& errMsg, const FString& methodMsg, const FString& propMsg)
{
	OnBadMethod(errMsg, methodMsg, propMsg);
}

