// Copyright (c) 2025 Mark Anthony Taylor. All rights reserved. Email: mark.anthony.taylor@gmail.com.
// Bundle generated by Build.Rococo.GUI.cs on Oct 2025 UTC
#pragma once

// Origin: D:\work\rococo\source\rococo\sexy\Common\sexy.stdstrings.h
#ifndef SEXY_STDSTRINGS_H
#define SEXY_STDSTRINGS_H

#include <string>

#include <rococo.strings.h>
#include <rococo.sexy.allocators.h>

namespace Rococo
{
	using rstdstring = std::basic_string<char, std::char_traits<char>, Rococo::Memory::SexyAllocator<char>>;
	using stdstring = rstdstring;
}

#endif // SEXY_STDSTRINGS_H
