// Copyright (c) 2025 Mark Anthony Taylor. All rights reserved. Email: mark.anthony.taylor@gmail.com.
// Bundle generated by Build.Rococo.GUI.cs on Oct 2025 UTC
// Origin: D:\work\rococo\UE5\RococoTestFPS\Plugins\RococoGui\Source\RococoGui\Public\ReflectedGameOptionsBuilder.h
// Copyright (c) 2025 Mark Anthony Taylor. All rights reserved. Email: mark.anthony.taylor@gmail.com.
#pragma once
#include <CoreMinimal.h>

namespace Rococo::GreatSex
{
	struct IGreatSexGenerator;

	struct IReflectedGameOptionsBuilder
	{
		virtual void AddMethods(UObject& object) = 0;
		virtual void Free() = 0;
		virtual void ReflectIntoGenerator(UObject& object, const FString& optionCategory, IGreatSexGenerator& generator) = 0;
	};

	ROCOCO_GUI_API IReflectedGameOptionsBuilder* CreateReflectedGameOptionsBuilder();
}
