// Copyright (c) 2025 Mark Anthony Taylor. All rights reserved. Email: mark.anthony.taylor@gmail.com.
// Bundle generated by Build.Rococo.GUI.cs on Oct 2025 UTC
#pragma once

// Origin: D:\work\rococo\source\rococo\include\rococo.SI.h
// Copyright (c)2025 Mark Anthony Taylor. Email: mark.anthony.taylor@gmail.com. All rights reserved.
#pragma once

#include <rococo.types.h>

namespace Rococo
{
	struct Kilograms
	{
		float value;
		FORCE_INLINE operator float() const { return value; }
	};

	FORCE_INLINE Kilograms operator "" _kg(long double value)
	{
		return Kilograms{ (float)value };
	}

	struct Metres
	{
		float value;
		FORCE_INLINE operator float() const { return value; }
	};

	FORCE_INLINE Metres operator "" _metres(long double value)
	{
		return Metres{ (float)value };
	}


	FORCE_INLINE Metres operator "" _metres(unsigned long long value)
	{
		return Metres{ (float)value };
	}

	struct Seconds
	{
		float value;
		FORCE_INLINE operator float() const { return value; }
	};

	FORCE_INLINE Seconds operator "" _seconds(long double value)
	{
		return Seconds{ (float)value };
	}

	struct MetresPerSecond
	{
		float value;
		FORCE_INLINE operator float() const { return value; }
	};

	FORCE_INLINE MetresPerSecond operator "" _mps(long double value)
	{
		return MetresPerSecond{ (float)value };
	}
}
