// Copyright (c) 2025 Mark Anthony Taylor. All rights reserved. Email: mark.anthony.taylor@gmail.com.
// Bundle generated by Build.Rococo.GUI.cs on Oct 2025 UTC
#pragma once

// Origin: D:\work\rococo\source\rococo\include\sexy.vector.h
// Copyright (c)2025 Mark Anthony Taylor. Email: mark.anthony.taylor@gmail.com. All rights reserved.
#pragma once
#include <rococo.sexy.allocators.h>
#include <vector>

namespace Rococo
{
	template<typename VALUE_>
	using TSexyVector = std::vector<VALUE_, Rococo::Memory::SexyAllocator<VALUE_>>;
}
