// Copyright (c) 2025 Mark Anthony Taylor. All rights reserved. Email: mark.anthony.taylor@gmail.com.
// Bundle generated by Build.Rococo.GUI.cs on Oct 2025 UTC
// Origin: D:\work\rococo\UE5\RococoTestFPS\Plugins\RococoGui\Source\RococoGui\Public\SRococoGRHostWidget.h
// Copyright (c) 2025 Mark Anthony Taylor. All rights reserved. Email: mark.anthony.taylor@gmail.com.
#pragma once
#include <Widgets/SLeafWidget.h>

#include "rococo.GR.UE5.h"
#include <RococoGuiAPI.h>

namespace Rococo
{
	template<class T> struct IEventCallback;
}

namespace Rococo::GreatSex
{
	struct IGreatSexGenerator;
}

namespace Rococo::Gui
{
	struct IUE5_GlobalFontMetrics;
}

class FPaintArgs;
class FSlateWindowElementList;
class UTexture;

using TMapPathToTexture = TMap<FString, UTexture2D*>;

ROCOCO_INTERFACE ISRococoGRHostWidgetEventHandler
{
	virtual void OnGRSystemConstructed(Rococo::Gui::IUE5_GRCustodianSupervisor& custodian, Rococo::Gui::IGRSystem& gr) = 0;
};

class SRococoGRHostWidget : public SLeafWidget
{
private:
	// OnPaint is a const function, and we need to access the none const API, so make our Gui retained system mutable
	mutable Rococo::AutoFree<Rococo::Gui::IGRSystemSupervisor> grSystem;
	mutable Rococo::AutoFree<Rococo::Gui::IUE5_GRCustodianSupervisor> custodian;

public:
	SLATE_BEGIN_ARGS(SRococoGRHostWidget)
	{}
	SLATE_END_ARGS()

	SRococoGRHostWidget();

	// Returns the custodian. Note that it may be null if SyncCustodian has not been invoked
	// Custodian functions and anything linked to them may throw exceptions, so only call in a pluin with exceptions enabled and captured
	Rococo::Gui::IUE5_GRCustodianSupervisor* GetCustodian()
	{
		return custodian;
	}

	Rococo::Gui::IGRSystem* GR()
	{
		return grSystem;
	}

	// Slate widgets are volatile, so store the mapPathToTexture elsewhere and sync our Custodian to it just after construction
	void SyncCustodian(UObject* worldObject, TMapPathToTexture& mapPathToTexture, const FSoftObjectPath& font, bool useDefaultFocus, ISRococoGRHostWidgetEventHandler& onConstruct, Rococo::Gui::IUE5_GlobalFontMetrics& fontMetrics);

	void Construct(const FArguments& args);
	FVector2D ComputeDesiredSize(float) const override;
	int32 OnPaint(const FPaintArgs& args, const FGeometry& allottedGeometry, const FSlateRect& cullingRect, OUT FSlateWindowElementList& drawElements, int32 LayerId, const FWidgetStyle& widgetStyle, bool bParentEnabled) const override;

	void LoadFrame(const char* pingPath, Rococo::IEventCallback<Rococo::GreatSex::IGreatSexGenerator>& onPrepForLoading);

	void Tick(const FGeometry& geometry, const double t, const float dt) override;
};

